name: Notificar a ntfy.sh

on:
  push:
    branches:
      - main

jobs:
  enviar_alerta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Ejecutar hola.js (si existe)
        run: |
          if [ -f "hola.js" ]; then
            node hola.js
          else
            echo "hola.js no encontrado, continuando de todos modos."
          fi

      - name: Enviar notificación a ntfy.sh
        run: |
          curl -H "Title: 🚀 Nuevo Push en main" \
               -H "Priority: high" \
               -d "Se subieron cambios al repositorio en la rama main." \
               https://ntfy.sh/devops-itla
